# permissions for end users to view poduis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podui-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-ui
    app.kubernetes.io/part-of: pod-ui
    app.kubernetes.io/managed-by: kustomize
  name: podui-viewer-role
rules:
- apiGroups:
  - scality.pod-ui.com
  resources:
  - poduis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scality.pod-ui.com
  resources:
  - poduis/status
  verbs:
  - get
