---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - scality.pod-ui.com
  resources:
  - poduis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scality.pod-ui.com
  resources:
  - poduis/finalizers
  verbs:
  - update
- apiGroups:
  - scality.pod-ui.com
  resources:
  - poduis/status
  verbs:
  - get
  - patch
  - update
